### ISSUE TITLE
difftastic-magit-show results in several errors: no such file and external diff died. 

### ISSUE THREAD

**Issue by drewverlee** [pkryger/difftastic.el#10]
in this picture, you can see me calling difftastic-magit-show on the git commit.

![image](https://github.com/user-attachments/assets/b4c9d071-9071-4b48-8d29-70a31d4b93e8)

I hope to get a diffstastic view of the changes from the last commit. Instead i get:

![image](https://github.com/user-attachments/assets/b2be6fd5-b212-4c01-b333-1c0b898bd18c)

What more information can i provide?

**Comment by pkryger** [comment]
Hello @drewverlee! Thanks for the report. I think the actions you take should produce desired outcome, i.e., show you changes from last commit.

From the screenshots I suspect that something's off with the `git` process (that runs `difft`) that is supposed to create an actual diff. You can see that `git` has produced a nice header with commit hash, author, date, and comment. However the `difft` portion has died for some reason.

To verify that assumption, could you please make sure you have the most recent `difftastic` installed (`difft --version`, ATM it's 0.59.0) and then run the following command in your terminal::
```
GIT_EXTERNAL_DIFF=difft git show --ext-diff c487a59
```

**Comment by drewverlee** [comment]
```
> ➜  foobar git:(master) ✗ GIT_EXTERNAL_DIFF=difft git show --ext-diff c487a59 
```
 
 results in
 
 ```
 commit c487a59a8141ff39d9c622e39a5bfc898840a2a2 (HEAD -> master)
Author: drew verlee <drew.verlee@gmail.com>
Date:   Wed Jul 24 20:53:10 2024 -0500

    if branch

No such file: /tmp/SZENFW_core.clj
No such file: /tmp/6er0EW_core.clj
fatal: external diff died, stopping at src/foobar/core.clj
```

here is the version:

```
➜  foobar git:(master) ✗ difft --version
Difftastic 0.59.0 (ffe27c575 2024-07-20, built with rustc 1.65.0)
```

I built it using ubuntu snaps and then aliased difftastic to difft

**Comment by pkryger** [comment]
I interpret this results as an indicator of an issue with [`difftastic`](https://github.com/Wilfred/difftastic) itself. Unfortunately, I have no capacity to debug it further. Perhaps you can rise an issue in [the upstream](https://github.com/Wilfred/difftastic)?

**Comment by drewverlee** [comment]
It's not an upstream issue with difftastic because after I reinstalled difftastic using linuxbrew (as opposed to snap) I can trigger difftastic from the command line:

```
GIT_EXTERNAL_DIFF=difft git show --ext-diff c487a59  
```
And get the desired result:

![image](https://github.com/user-attachments/assets/94fcc049-2855-41ca-8e03-bde71277c75c)


However still no luck from emacs. It can't find the program difft. the relevnet bit of the errort below is "difft: not found"

```
commit c487a59a8141ff39d9c622e39a5bfc898840a2a2 (HEAD -> master)
Author: drew verlee <drew.verlee@gmail.com>
Date:   Wed Jul 24 20:53:10 2024 -0500

    if branch

difft --color always --width 144 --background dark: 1: difft: not found
fatal: external diff died, stopping at src/foobar/core.clj

```


 However if i use the emacs project shell, it can find it. Where is the package looking for difft? ill look into this further.

**Comment by drewverlee** [comment]
If there is anything to improve here, it's unclear to me. I think i made a  ~/tmp directory at one point and then the error message more clearly showed the issue was it couldn't find difft on the cli, and which point is was more clear to me what I had to do. 

ill leave this open, but feel free to close it if it's no longer useful.

**Comment by pkryger** [comment]
Thank you for reporting back. And glad you solved the issue. FWIW, the package uses `difftastic-executable` variable to locate the `difftastic` executable. It defaults to `difft`. Not sure why Emacs started in the old session was not able to locate the new executable. But seems to work now. Closing.
