### ISSUE TITLE
Minimum required magit version

### ISSUE THREAD

**Issue by svraka** [pkryger/difftastic.el#11]
Thanks for this great package!

Currently, difftastic.el depends on magit version "20220326". If a user prefers to install packages from a stable source (ELPA, or MELPA stable), along with other MELPA packages, install difftastic will update magit. Did you specify this dependency because magit didn't make a stable release for a long time? If so, would you consider changing the dependency to the latest stable, given the recent v4 magit releases?

**Comment by pkryger** [comment]
Thank you for reminding me - I was to do it at some point. I guess now is as good as ever. Lack of stable release with sufficient functionality was exactly the reason, please see 4fb0528156e73cfaa7fc1fec5958185391dc0deb for more context.
