### ISSUE TITLE
Invalid language due to single quotes

### ISSUE THREAD

**Issue by ashlineldridge** [pkryger/difftastic.el#12]
Hi, thanks for the package. The commit 5b22afe has broken `difftastic-buffers` for me. If I run `difftastic-buffers` against two JSON buffers and select "JSON" as the language override, I get the following error message:

```
No such language ''JSON''
See --list-languages for the names of all languages available. Language overrides are case insensitive.
```

The function `difftastic--build-files-command` is passing the added single quotes through to the `difft` executable. At first, I thought it might be assumed that `shell-command-switch` included the `-i` switch but I tried this and still get the error above. If I modify the `difftastic--build-files-command` function so that it no longer quotes the language then things work as expected.

**Comment by pkryger** [comment]
@ashlineldridge thank you very much for the report. I think I was doing some fiddling with `shell-command-to-string` around that time and mistakenly quoted the chosen language when the parameters are passed to `make-process`. I was able to reproduce the same error locally, and after commit reversion the error has disappeared. Updated version should be on MELPA now. Please let me know if you still see issues.

**Comment by ashlineldridge** [comment]
Thanks for the quick fix, @pkryger! New version works for me as well 🙌🏽
